name: crossover_reward_app
description: Crossover Reward App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: ^6.1.2
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.2
  gap: ^3.0.0
  get_it: ^7.6.0
  go_router: ^7.0.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  logging: ^1.1.1
  money_formatter: ^0.0.4
  package_info_plus: ^4.0.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/svgs/
    - assets/images/pngs/
